export const DEPARTURES_ACTION_TYPES = {
  FETCH_DEPARTURES_START: "departures/FETCH_DEPARTURES_START",
  FETCH_DEPARTURES_SUCCESS: "departures/FETCH_DEPARTURES_SUCCESS",
  FETCH_DEPARTURES_FAILED: "departures/FETCH_DEPARTURES_FAILED",
};
