export const DISRUPTIONS_ACTION_TYPES = {
  FETCH_DISRUPTIONS_START: "disruptions/FETCH_DISRUPTIONS_START",
  FETCH_DISRUPTIONS_SUCCESS: "disruptions/FETCH_DISRUPTIONS_SUCCESS",
  FETCH_DISRUPTIONS_FAILED: "disruptions/FETCH_DISRUPTIONS_FAILED",
};
